spring.application.name=minimarket
# Configuraci�n de H2 en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Configuraci�n de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
# Permite que data.sql se ejecute DESPU�S de que Hibernate cree las tablas
spring.jpa.defer-datasource-initialization=true

# Configuraci�n JWT
# Clave secreta en Base64 (m�nimo 256 bits para HS256)
jwt.secret=bWluaW1hcmtldC1wbHVzLXNlY3JldC1rZXktc3ByaW5nLXNlY3VyaXR5LTIwMjQ=
# Expiraci�n del token en milisegundos (24 horas)
jwt.expiration=86400000
